uRos presentation abstract
Big-Life-Lab/cchsflow pull request #120
Opened 2022-09-08 13:12 UTC by wyusuf068

Abstract for uRos2022 virtual event.

2022-09-08 13:53 UTC, DougManuel requested changes
I committed suggestions.

2022-09-09 12:26 UTC, yulric approved these changes

2022-09-14 11:18 UTC, CBjerke approved these changes
Made some edits to the most recent version of the abstract.

2022-09-14 17:59 UTC, DougManuel approved these changes

2022-09-14 17:59 UTC, merged