Added ADL_score_5 derived variable
Big-Life-Lab/cchsflow pull request #74
Opened 2020-10-23 00:09 UTC by yulric

2020-10-27 11:29 UTC, wyusuf068 commented on R/adl-score-5.R
> +#' which are common accros CCHS cycles from 2201 to 2014:
From 2001 to 2014.

2020-10-27 11:32 UTC, wyusuf068 commented on R/adl-score-5.R
> +      ifelse(ADL_01 == "NA::b", count_missing_adl + 1, count_missing_adl)
NA::b is missing. Did you mean to say NA::a to check for "not applicable"?

2020-10-27 11:35 UTC, wyusuf068 commented on R/adl-score-5.R
> +    # values in each row
Count the total number of not applicable values in each row.

2020-10-27 11:37 UTC, wyusuf068 approved these changes
Looks good to me. A few minor documentation fixes before merging to `dev`.

2020-10-27 16:04 UTC, CBjerke approved these changes
Agree with Warsame's comments re edits

2020-10-28 13:37 UTC, yulric commented
@wyusuf068 I've made the changes you proposed. Let me know if it all looks good.

2020-10-28 18:02 UTC, DougManuel requested changes
No clear best approach, but I suggest that we have a NA category if there is NA for any component. See the screenshot for SCHDSTG below. 

In practice, I would impute missing for the individual questions before calculating this measure, but the imputation practice is not part of cchsflow and there is no definitive approach to address missing data. Allowing a flexible approach to missing data is important and the current or the suggested revision are both flexible.

@CBjerke I reviewed how Statscan considers missing data in derived variables such as `PACDEE` (METS of physical activity) and `SCHDSTG` (Smoking - Stages of change). I'm not sure there is a consistent approach or at least the approach to consider missing data depends on the context of the question. More broadly, there is not a consistent approach that people use for any variable in CCHS. e.g. do you include or exclude NA when estimating the prevalence of smoking? 

For PACDEE, if you assigned a value of zero METS for a specific activity if you are a non-respondent to a specific activity (e.g. gardening). 

For SCHDSTG, if you are assigned NA to the overall score if you respond to NA for any component. 

<img width="987" alt="Screen Shot 2020-10-28 at 1 33 14 PM" src="https://user-images.githubusercontent.com/13246138/97476419-bf10d300-1924-11eb-941a-7dfc53d539e2.png">

2020-10-29 11:23 UTC, yulric commented on R/adl-score-5.R
> +#' A value of NA::a means that all the input variables had NA::a
@DougManuel Not sure what you mean? I though NA::c meant not asked in the survey, NA::a is not applicable.

2020-10-29 11:23 UTC, yulric commented on R/adl-score-5.R
> +#' # Let's say you do not need help preparing meals, you need help getting to
I copied this from Warsame's example for ADL_der and just changed it for this score haha.

2020-10-29 11:26 UTC, yulric commented
@DougManuel Should the priority be to set "NA::b" or "NA::a"? i.e. if a individual has missing data for ADL_01 and "not applicable" data for ADL_02 what should the variable be set to?

2020-10-29 12:46 UTC, DougManuel commented
> @DougManuel Should the priority be to set "NA::b" or "NA::a"? i.e. if a individual has missing data for ADL_01 and "not applicable" data for ADL_02 what should the variable be set to?

Good question. Suggest NA::a 

I thought that we were transforming from the original cchs variables which have NA values of 6, 7, 8, etc. 

Suggest eight categories in total:

0 - Needs help with 0 tasks
1 - Needs help with at least 1 task
2 - Needs help with at least 2 tasks
3 - needs help with at least 3 tasks
4 - Needs help with at least 4 tasks
5 - Needs help with at least 5 tasks
NA::a - one or more ADL intermediate variables with NA::a
NA::b - one or more ADL intermediate variables with NA::b AND no variables with NA::a

2020-10-29 13:12 UTC, wyusuf068 commented on R/adl-score-5.R
> +#' A value of NA::a means that all the input variables had NA::a
Perhaps write: "#' A value of NA::a means that all the input variables had NA::a, not applicable."?

2020-10-29 13:27 UTC, wyusuf068 commented on R/adl-score-5.R
> +    # For each row in the ADL variables, count the total number of "not applicable"
count the total number of "missing" values in each row*

2020-10-30 12:11 UTC, yulric commented
@DougManuel @wyusuf068 Pushed your changes.

2020-10-30 13:30 UTC, DougManuel approved these changes
Looks very good.
- I made a few edit suggestions for the document. Some of the edit suggestions are to align with the documentation for other functions.

- There is [switch](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/switch) in base R and case_when in dyplr (a package dependency) that may work if you don't want the if-else statements.

2020-11-02 13:58 UTC, merged